{% set name = "llama-index-readers-file" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_readers_file-{{ version }}.tar.gz
    sha256: 7828dec1feb7c53e6d3140385f8499c0e7ac746265299384714ddfd163f9d15a
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - pandas
    - python >=3.8.1,<4.0
    - llama-index-core >=0.12.0,<0.13.0
    - beautifulsoup4 >=4.12.3,<5.0.0
    - pypdf >=5.1.0,<6.0.0
    - striprtf >=0.0.26,<0.0.27
  run_constrained:
    - pymupdf >=1.23.21,<2.0.0

test:
  imports:
    - llama_index.readers.file
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://llamaindex.ai
  summary: llama-index readers file integration
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/readers/llama-index-readers-file

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
